server:
  port: 5000
  
spring:
  datasource:
    url: jdbc:mysql://blog-db.cfksiuq4yevr.us-east-1.rds.amazonaws.com:3306/blog_app_apis
    username: ameya
    password: lcwdpassword

  jpa:
    show-sql: true
